# ELK + Ruby logstash-log test

version: '2'

services:
  logstash:
    build: ./logstash
    ports:
      - "9600:9600"
    links:
      - elasticsearch

  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"

  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
